// Generate the typed icon set from the standalone SVG sources. Reads every
// `src/app/shared/icon/icons/*.svg`, collapses each to a single trimmed line, and writes
// `src/app/shared/icon/icon-set.ts` — an `ICONS` map (name → SVG markup) plus the derived
// `IconName` union. The .ts is committed; regenerate on demand (`make gen-icons` / `npm run
// gen:icons`) whenever an SVG is added/changed. No dependencies — plain Node.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, basename } from 'node:path';
import { format, resolveConfig } from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const iconsDir = resolve(here, '../src/app/shared/icon/icons');
const out = resolve(here, '../src/app/shared/icon/icon-set.ts');

// Collapse a multi-line SVG to a single line: trim, drop whitespace between tags, and
// fold runs of whitespace (incl. newlines) into a single space.
const collapse = (svg) =>
  svg
    .trim()
    .replace(/>\s+</g, '><')
    .replace(/\s+/g, ' ')
    .replace(/\s*\/?>/g, (tagEnd) => (tagEnd.includes('/') ? ' />' : '>'));

const files = readdirSync(iconsDir)
  .filter((file) => file.endsWith('.svg'))
  .sort();

const entries = files.map((file) => {
  const name = basename(file, '.svg');
  const markup = collapse(readFileSync(resolve(iconsDir, file), 'utf8'));

  return `  '${name}': '${markup}',`;
});

const body = `// GENERATED by scripts/gen-icons.mjs — do not edit. Run \`make gen-icons\`.

export const ICONS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;

// Run the result through the repo's Prettier config so the committed file stays format-clean.
const prettierOptions = await resolveConfig(out);
const formatted = await format(body, { ...prettierOptions, filepath: out });

writeFileSync(out, formatted);
console.log(`✓ icon-set.ts (${files.length} icons) → ${out}`);
