// GENERATED by scripts/gen-article-bodies.mjs — do not edit. Run `make gen-article-bodies`.

import type { Lang } from '../../domain';

import angularDeferControlFlowEn from '../../../content/articles/angular-defer-control-flow.en.md';
import angularDeferControlFlowFr from '../../../content/articles/angular-defer-control-flow.fr.md';
import angularResourceHttpresourceEn from '../../../content/articles/angular-resource-httpresource.en.md';
import angularResourceHttpresourceFr from '../../../content/articles/angular-resource-httpresource.fr.md';
import angularSignalstoreNgrxEn from '../../../content/articles/angular-signalstore-ngrx.en.md';
import angularSignalstoreNgrxFr from '../../../content/articles/angular-signalstore-ngrx.fr.md';
import angularSsgAzureStaticWebAppsEn from '../../../content/articles/angular-ssg-azure-static-web-apps.en.md';
import angularSsgAzureStaticWebAppsFr from '../../../content/articles/angular-ssg-azure-static-web-apps.fr.md';
import angularZonelessSignalsEn from '../../../content/articles/angular-zoneless-signals.en.md';
import angularZonelessSignalsFr from '../../../content/articles/angular-zoneless-signals.fr.md';
import azureContainerAppsDotnetEn from '../../../content/articles/azure-container-apps-dotnet.en.md';
import azureContainerAppsDotnetFr from '../../../content/articles/azure-container-apps-dotnet.fr.md';
import azureKeyVaultManagedIdentityEn from '../../../content/articles/azure-key-vault-managed-identity.en.md';
import azureKeyVaultManagedIdentityFr from '../../../content/articles/azure-key-vault-managed-identity.fr.md';
import cqrsVerticalSlicesDotnetEn from '../../../content/articles/cqrs-vertical-slices-dotnet.en.md';
import cqrsVerticalSlicesDotnetFr from '../../../content/articles/cqrs-vertical-slices-dotnet.fr.md';
import dockerMultistageDotnetAngularEn from '../../../content/articles/docker-multistage-dotnet-angular.en.md';
import dockerMultistageDotnetAngularFr from '../../../content/articles/docker-multistage-dotnet-angular.fr.md';
import dotnetGrpcMicroservicesEn from '../../../content/articles/dotnet-grpc-microservices.en.md';
import dotnetGrpcMicroservicesFr from '../../../content/articles/dotnet-grpc-microservices.fr.md';
import dotnetSourceGeneratorsEn from '../../../content/articles/dotnet-source-generators.en.md';
import dotnetSourceGeneratorsFr from '../../../content/articles/dotnet-source-generators.fr.md';
import etranglerLeMonolitheDotnetEn from '../../../content/articles/etrangler-le-monolithe-dotnet.en.md';
import etranglerLeMonolitheDotnetFr from '../../../content/articles/etrangler-le-monolithe-dotnet.fr.md';
import flutterFirebaseOfflineFirstEn from '../../../content/articles/flutter-firebase-offline-first.en.md';
import flutterFirebaseOfflineFirstFr from '../../../content/articles/flutter-firebase-offline-first.fr.md';
import flutterMelosMonorepoEn from '../../../content/articles/flutter-melos-monorepo.en.md';
import flutterMelosMonorepoFr from '../../../content/articles/flutter-melos-monorepo.fr.md';
import flutterRiverpodArchitectureEn from '../../../content/articles/flutter-riverpod-architecture.en.md';
import flutterRiverpodArchitectureFr from '../../../content/articles/flutter-riverpod-architecture.fr.md';
import minimalApiEfCoreDotnet8En from '../../../content/articles/minimal-api-ef-core-dotnet8.en.md';
import minimalApiEfCoreDotnet8Fr from '../../../content/articles/minimal-api-ef-core-dotnet8.fr.md';
import moteurDoomSoftwareWebgpuEn from '../../../content/articles/moteur-doom-software-webgpu.en.md';
import moteurDoomSoftwareWebgpuFr from '../../../content/articles/moteur-doom-software-webgpu.fr.md';
import ngsharpMoteurTemplatesInterpreteEn from '../../../content/articles/ngsharp-moteur-templates-interprete.en.md';
import ngsharpMoteurTemplatesInterpreteFr from '../../../content/articles/ngsharp-moteur-templates-interprete.fr.md';
import opentelemetryObservabiliteDotnetEn from '../../../content/articles/opentelemetry-observabilite-dotnet.en.md';
import opentelemetryObservabiliteDotnetFr from '../../../content/articles/opentelemetry-observabilite-dotnet.fr.md';
import orchestrationSansBaseGraphqlDotnetEn from '../../../content/articles/orchestration-sans-base-graphql-dotnet.en.md';
import orchestrationSansBaseGraphqlDotnetFr from '../../../content/articles/orchestration-sans-base-graphql-dotnet.fr.md';
import pipelineCicdGithubActionsAzureEn from '../../../content/articles/pipeline-cicd-github-actions-azure.en.md';
import pipelineCicdGithubActionsAzureFr from '../../../content/articles/pipeline-cicd-github-actions-azure.fr.md';
import sqlExternaliseMigrationsEfCoreEn from '../../../content/articles/sql-externalise-migrations-ef-core.en.md';
import sqlExternaliseMigrationsEfCoreFr from '../../../content/articles/sql-externalise-migrations-ef-core.fr.md';
import universeMapMoteurEclipsesEn from '../../../content/articles/universe-map-moteur-eclipses.en.md';
import universeMapMoteurEclipsesFr from '../../../content/articles/universe-map-moteur-eclipses.fr.md';

/** slug → raw Markdown body per language. Single source for render + prerender. */
export const ARTICLE_BODIES: Record<string, Record<Lang, string>> = {
  'angular-defer-control-flow': { en: angularDeferControlFlowEn, fr: angularDeferControlFlowFr },
  'angular-resource-httpresource': { en: angularResourceHttpresourceEn, fr: angularResourceHttpresourceFr },
  'angular-signalstore-ngrx': { en: angularSignalstoreNgrxEn, fr: angularSignalstoreNgrxFr },
  'angular-ssg-azure-static-web-apps': { en: angularSsgAzureStaticWebAppsEn, fr: angularSsgAzureStaticWebAppsFr },
  'angular-zoneless-signals': { en: angularZonelessSignalsEn, fr: angularZonelessSignalsFr },
  'azure-container-apps-dotnet': { en: azureContainerAppsDotnetEn, fr: azureContainerAppsDotnetFr },
  'azure-key-vault-managed-identity': { en: azureKeyVaultManagedIdentityEn, fr: azureKeyVaultManagedIdentityFr },
  'cqrs-vertical-slices-dotnet': { en: cqrsVerticalSlicesDotnetEn, fr: cqrsVerticalSlicesDotnetFr },
  'docker-multistage-dotnet-angular': { en: dockerMultistageDotnetAngularEn, fr: dockerMultistageDotnetAngularFr },
  'dotnet-grpc-microservices': { en: dotnetGrpcMicroservicesEn, fr: dotnetGrpcMicroservicesFr },
  'dotnet-source-generators': { en: dotnetSourceGeneratorsEn, fr: dotnetSourceGeneratorsFr },
  'etrangler-le-monolithe-dotnet': { en: etranglerLeMonolitheDotnetEn, fr: etranglerLeMonolitheDotnetFr },
  'flutter-firebase-offline-first': { en: flutterFirebaseOfflineFirstEn, fr: flutterFirebaseOfflineFirstFr },
  'flutter-melos-monorepo': { en: flutterMelosMonorepoEn, fr: flutterMelosMonorepoFr },
  'flutter-riverpod-architecture': { en: flutterRiverpodArchitectureEn, fr: flutterRiverpodArchitectureFr },
  'minimal-api-ef-core-dotnet8': { en: minimalApiEfCoreDotnet8En, fr: minimalApiEfCoreDotnet8Fr },
  'moteur-doom-software-webgpu': { en: moteurDoomSoftwareWebgpuEn, fr: moteurDoomSoftwareWebgpuFr },
  'ngsharp-moteur-templates-interprete': { en: ngsharpMoteurTemplatesInterpreteEn, fr: ngsharpMoteurTemplatesInterpreteFr },
  'opentelemetry-observabilite-dotnet': { en: opentelemetryObservabiliteDotnetEn, fr: opentelemetryObservabiliteDotnetFr },
  'orchestration-sans-base-graphql-dotnet': { en: orchestrationSansBaseGraphqlDotnetEn, fr: orchestrationSansBaseGraphqlDotnetFr },
  'pipeline-cicd-github-actions-azure': { en: pipelineCicdGithubActionsAzureEn, fr: pipelineCicdGithubActionsAzureFr },
  'sql-externalise-migrations-ef-core': { en: sqlExternaliseMigrationsEfCoreEn, fr: sqlExternaliseMigrationsEfCoreFr },
  'universe-map-moteur-eclipses': { en: universeMapMoteurEclipsesEn, fr: universeMapMoteurEclipsesFr },
};
