// GENERATED by scripts/gen-article-bodies.mjs — do not edit. Run `make gen-article-bodies`.

import type { Lang } from '../../domain';

import angularDeferControlFlowDe from '../../../content/articles/angular-defer-control-flow.de.md';
import angularDeferControlFlowEn from '../../../content/articles/angular-defer-control-flow.en.md';
import angularDeferControlFlowEs from '../../../content/articles/angular-defer-control-flow.es.md';
import angularDeferControlFlowFr from '../../../content/articles/angular-defer-control-flow.fr.md';
import angularResourceHttpresourceDe from '../../../content/articles/angular-resource-httpresource.de.md';
import angularResourceHttpresourceEn from '../../../content/articles/angular-resource-httpresource.en.md';
import angularResourceHttpresourceEs from '../../../content/articles/angular-resource-httpresource.es.md';
import angularResourceHttpresourceFr from '../../../content/articles/angular-resource-httpresource.fr.md';
import angularSignalstoreNgrxDe from '../../../content/articles/angular-signalstore-ngrx.de.md';
import angularSignalstoreNgrxEn from '../../../content/articles/angular-signalstore-ngrx.en.md';
import angularSignalstoreNgrxEs from '../../../content/articles/angular-signalstore-ngrx.es.md';
import angularSignalstoreNgrxFr from '../../../content/articles/angular-signalstore-ngrx.fr.md';
import angularSsgAzureStaticWebAppsDe from '../../../content/articles/angular-ssg-azure-static-web-apps.de.md';
import angularSsgAzureStaticWebAppsEn from '../../../content/articles/angular-ssg-azure-static-web-apps.en.md';
import angularSsgAzureStaticWebAppsEs from '../../../content/articles/angular-ssg-azure-static-web-apps.es.md';
import angularSsgAzureStaticWebAppsFr from '../../../content/articles/angular-ssg-azure-static-web-apps.fr.md';
import angularZonelessSignalsDe from '../../../content/articles/angular-zoneless-signals.de.md';
import angularZonelessSignalsEn from '../../../content/articles/angular-zoneless-signals.en.md';
import angularZonelessSignalsEs from '../../../content/articles/angular-zoneless-signals.es.md';
import angularZonelessSignalsFr from '../../../content/articles/angular-zoneless-signals.fr.md';
import azureContainerAppsDotnetDe from '../../../content/articles/azure-container-apps-dotnet.de.md';
import azureContainerAppsDotnetEn from '../../../content/articles/azure-container-apps-dotnet.en.md';
import azureContainerAppsDotnetEs from '../../../content/articles/azure-container-apps-dotnet.es.md';
import azureContainerAppsDotnetFr from '../../../content/articles/azure-container-apps-dotnet.fr.md';
import azureKeyVaultManagedIdentityDe from '../../../content/articles/azure-key-vault-managed-identity.de.md';
import azureKeyVaultManagedIdentityEn from '../../../content/articles/azure-key-vault-managed-identity.en.md';
import azureKeyVaultManagedIdentityEs from '../../../content/articles/azure-key-vault-managed-identity.es.md';
import azureKeyVaultManagedIdentityFr from '../../../content/articles/azure-key-vault-managed-identity.fr.md';
import cqrsVerticalSlicesDotnetDe from '../../../content/articles/cqrs-vertical-slices-dotnet.de.md';
import cqrsVerticalSlicesDotnetEn from '../../../content/articles/cqrs-vertical-slices-dotnet.en.md';
import cqrsVerticalSlicesDotnetEs from '../../../content/articles/cqrs-vertical-slices-dotnet.es.md';
import cqrsVerticalSlicesDotnetFr from '../../../content/articles/cqrs-vertical-slices-dotnet.fr.md';
import dockerMultistageDotnetAngularDe from '../../../content/articles/docker-multistage-dotnet-angular.de.md';
import dockerMultistageDotnetAngularEn from '../../../content/articles/docker-multistage-dotnet-angular.en.md';
import dockerMultistageDotnetAngularEs from '../../../content/articles/docker-multistage-dotnet-angular.es.md';
import dockerMultistageDotnetAngularFr from '../../../content/articles/docker-multistage-dotnet-angular.fr.md';
import dotnetGrpcMicroservicesDe from '../../../content/articles/dotnet-grpc-microservices.de.md';
import dotnetGrpcMicroservicesEn from '../../../content/articles/dotnet-grpc-microservices.en.md';
import dotnetGrpcMicroservicesEs from '../../../content/articles/dotnet-grpc-microservices.es.md';
import dotnetGrpcMicroservicesFr from '../../../content/articles/dotnet-grpc-microservices.fr.md';
import dotnetSourceGeneratorsDe from '../../../content/articles/dotnet-source-generators.de.md';
import dotnetSourceGeneratorsEn from '../../../content/articles/dotnet-source-generators.en.md';
import dotnetSourceGeneratorsEs from '../../../content/articles/dotnet-source-generators.es.md';
import dotnetSourceGeneratorsFr from '../../../content/articles/dotnet-source-generators.fr.md';
import etranglerLeMonolitheDotnetDe from '../../../content/articles/etrangler-le-monolithe-dotnet.de.md';
import etranglerLeMonolitheDotnetEn from '../../../content/articles/etrangler-le-monolithe-dotnet.en.md';
import etranglerLeMonolitheDotnetEs from '../../../content/articles/etrangler-le-monolithe-dotnet.es.md';
import etranglerLeMonolitheDotnetFr from '../../../content/articles/etrangler-le-monolithe-dotnet.fr.md';
import flutterFirebaseOfflineFirstDe from '../../../content/articles/flutter-firebase-offline-first.de.md';
import flutterFirebaseOfflineFirstEn from '../../../content/articles/flutter-firebase-offline-first.en.md';
import flutterFirebaseOfflineFirstEs from '../../../content/articles/flutter-firebase-offline-first.es.md';
import flutterFirebaseOfflineFirstFr from '../../../content/articles/flutter-firebase-offline-first.fr.md';
import flutterMelosMonorepoDe from '../../../content/articles/flutter-melos-monorepo.de.md';
import flutterMelosMonorepoEn from '../../../content/articles/flutter-melos-monorepo.en.md';
import flutterMelosMonorepoEs from '../../../content/articles/flutter-melos-monorepo.es.md';
import flutterMelosMonorepoFr from '../../../content/articles/flutter-melos-monorepo.fr.md';
import flutterRiverpodArchitectureDe from '../../../content/articles/flutter-riverpod-architecture.de.md';
import flutterRiverpodArchitectureEn from '../../../content/articles/flutter-riverpod-architecture.en.md';
import flutterRiverpodArchitectureEs from '../../../content/articles/flutter-riverpod-architecture.es.md';
import flutterRiverpodArchitectureFr from '../../../content/articles/flutter-riverpod-architecture.fr.md';
import minimalApiEfCoreDotnet8De from '../../../content/articles/minimal-api-ef-core-dotnet8.de.md';
import minimalApiEfCoreDotnet8En from '../../../content/articles/minimal-api-ef-core-dotnet8.en.md';
import minimalApiEfCoreDotnet8Es from '../../../content/articles/minimal-api-ef-core-dotnet8.es.md';
import minimalApiEfCoreDotnet8Fr from '../../../content/articles/minimal-api-ef-core-dotnet8.fr.md';
import opentelemetryObservabiliteDotnetDe from '../../../content/articles/opentelemetry-observabilite-dotnet.de.md';
import opentelemetryObservabiliteDotnetEn from '../../../content/articles/opentelemetry-observabilite-dotnet.en.md';
import opentelemetryObservabiliteDotnetEs from '../../../content/articles/opentelemetry-observabilite-dotnet.es.md';
import opentelemetryObservabiliteDotnetFr from '../../../content/articles/opentelemetry-observabilite-dotnet.fr.md';
import pipelineCicdGithubActionsAzureDe from '../../../content/articles/pipeline-cicd-github-actions-azure.de.md';
import pipelineCicdGithubActionsAzureEn from '../../../content/articles/pipeline-cicd-github-actions-azure.en.md';
import pipelineCicdGithubActionsAzureEs from '../../../content/articles/pipeline-cicd-github-actions-azure.es.md';
import pipelineCicdGithubActionsAzureFr from '../../../content/articles/pipeline-cicd-github-actions-azure.fr.md';
import testerAngularZonelessVitestDe from '../../../content/articles/tester-angular-zoneless-vitest.de.md';
import testerAngularZonelessVitestEn from '../../../content/articles/tester-angular-zoneless-vitest.en.md';
import testerAngularZonelessVitestEs from '../../../content/articles/tester-angular-zoneless-vitest.es.md';
import testerAngularZonelessVitestFr from '../../../content/articles/tester-angular-zoneless-vitest.fr.md';
import tutoGitRebaseInteractifDe from '../../../content/articles/tuto-git-rebase-interactif.de.md';
import tutoGitRebaseInteractifEn from '../../../content/articles/tuto-git-rebase-interactif.en.md';
import tutoGitRebaseInteractifEs from '../../../content/articles/tuto-git-rebase-interactif.es.md';
import tutoGitRebaseInteractifFr from '../../../content/articles/tuto-git-rebase-interactif.fr.md';

/** slug → raw Markdown body per language. Single source for render + prerender. */
export const ARTICLE_BODIES: Record<string, Record<Lang, string>> = {
  'angular-defer-control-flow': {
    de: angularDeferControlFlowDe,
    en: angularDeferControlFlowEn,
    es: angularDeferControlFlowEs,
    fr: angularDeferControlFlowFr,
  },
  'angular-resource-httpresource': {
    de: angularResourceHttpresourceDe,
    en: angularResourceHttpresourceEn,
    es: angularResourceHttpresourceEs,
    fr: angularResourceHttpresourceFr,
  },
  'angular-signalstore-ngrx': {
    de: angularSignalstoreNgrxDe,
    en: angularSignalstoreNgrxEn,
    es: angularSignalstoreNgrxEs,
    fr: angularSignalstoreNgrxFr,
  },
  'angular-ssg-azure-static-web-apps': {
    de: angularSsgAzureStaticWebAppsDe,
    en: angularSsgAzureStaticWebAppsEn,
    es: angularSsgAzureStaticWebAppsEs,
    fr: angularSsgAzureStaticWebAppsFr,
  },
  'angular-zoneless-signals': {
    de: angularZonelessSignalsDe,
    en: angularZonelessSignalsEn,
    es: angularZonelessSignalsEs,
    fr: angularZonelessSignalsFr,
  },
  'azure-container-apps-dotnet': {
    de: azureContainerAppsDotnetDe,
    en: azureContainerAppsDotnetEn,
    es: azureContainerAppsDotnetEs,
    fr: azureContainerAppsDotnetFr,
  },
  'azure-key-vault-managed-identity': {
    de: azureKeyVaultManagedIdentityDe,
    en: azureKeyVaultManagedIdentityEn,
    es: azureKeyVaultManagedIdentityEs,
    fr: azureKeyVaultManagedIdentityFr,
  },
  'cqrs-vertical-slices-dotnet': {
    de: cqrsVerticalSlicesDotnetDe,
    en: cqrsVerticalSlicesDotnetEn,
    es: cqrsVerticalSlicesDotnetEs,
    fr: cqrsVerticalSlicesDotnetFr,
  },
  'docker-multistage-dotnet-angular': {
    de: dockerMultistageDotnetAngularDe,
    en: dockerMultistageDotnetAngularEn,
    es: dockerMultistageDotnetAngularEs,
    fr: dockerMultistageDotnetAngularFr,
  },
  'dotnet-grpc-microservices': {
    de: dotnetGrpcMicroservicesDe,
    en: dotnetGrpcMicroservicesEn,
    es: dotnetGrpcMicroservicesEs,
    fr: dotnetGrpcMicroservicesFr,
  },
  'dotnet-source-generators': {
    de: dotnetSourceGeneratorsDe,
    en: dotnetSourceGeneratorsEn,
    es: dotnetSourceGeneratorsEs,
    fr: dotnetSourceGeneratorsFr,
  },
  'etrangler-le-monolithe-dotnet': {
    de: etranglerLeMonolitheDotnetDe,
    en: etranglerLeMonolitheDotnetEn,
    es: etranglerLeMonolitheDotnetEs,
    fr: etranglerLeMonolitheDotnetFr,
  },
  'flutter-firebase-offline-first': {
    de: flutterFirebaseOfflineFirstDe,
    en: flutterFirebaseOfflineFirstEn,
    es: flutterFirebaseOfflineFirstEs,
    fr: flutterFirebaseOfflineFirstFr,
  },
  'flutter-melos-monorepo': {
    de: flutterMelosMonorepoDe,
    en: flutterMelosMonorepoEn,
    es: flutterMelosMonorepoEs,
    fr: flutterMelosMonorepoFr,
  },
  'flutter-riverpod-architecture': {
    de: flutterRiverpodArchitectureDe,
    en: flutterRiverpodArchitectureEn,
    es: flutterRiverpodArchitectureEs,
    fr: flutterRiverpodArchitectureFr,
  },
  'minimal-api-ef-core-dotnet8': {
    de: minimalApiEfCoreDotnet8De,
    en: minimalApiEfCoreDotnet8En,
    es: minimalApiEfCoreDotnet8Es,
    fr: minimalApiEfCoreDotnet8Fr,
  },
  'opentelemetry-observabilite-dotnet': {
    de: opentelemetryObservabiliteDotnetDe,
    en: opentelemetryObservabiliteDotnetEn,
    es: opentelemetryObservabiliteDotnetEs,
    fr: opentelemetryObservabiliteDotnetFr,
  },
  'pipeline-cicd-github-actions-azure': {
    de: pipelineCicdGithubActionsAzureDe,
    en: pipelineCicdGithubActionsAzureEn,
    es: pipelineCicdGithubActionsAzureEs,
    fr: pipelineCicdGithubActionsAzureFr,
  },
  'tester-angular-zoneless-vitest': {
    de: testerAngularZonelessVitestDe,
    en: testerAngularZonelessVitestEn,
    es: testerAngularZonelessVitestEs,
    fr: testerAngularZonelessVitestFr,
  },
  'tuto-git-rebase-interactif': {
    de: tutoGitRebaseInteractifDe,
    en: tutoGitRebaseInteractifEn,
    es: tutoGitRebaseInteractifEs,
    fr: tutoGitRebaseInteractifFr,
  },
};
