import type { EnemySpec } from './enemy-art';

export const PINKY_SPEC: EnemySpec = {
  texName: 'PINKY_WALK',
  atlasUrl: '/game/enemies/pinky/pinky_walk_atlas.webp',
  walkCols: 4,
  walkRows: 5,
  deathTexName: 'PINKY_DEATH',
  deathUrl: '/game/enemies/pinky/pinky_death_atlas.webp',
  deathFrames: 6,
  deathFps: 9,
  attackTexName: 'PINKY_ATTACK',
  attackUrl: '/game/enemies/pinky/pinky_attack_atlas.webp',
  attackFrames: 5,
  attackFps: 16,
  painTexName: 'PINKY_PAIN',
  painUrl: '/game/enemies/pinky/pinky_pain_atlas.webp',
  aspect: 512 / 716,
  worldHeight: 1.8,
  walkStepRate: 4.5,
  hitRadius: 0.4,
  hp: 80,
  speed: 2.2,
  standoff: 0.7,
  windup: 0.3,
  cooldownTime: 1,
  meleeReach: 1.3,
  meleeDamage: 12,
};

export const SHOTGUNGUY_SPEC: EnemySpec = {
  texName: 'SHOTGUNGUY_WALK',
  atlasUrl: '/game/enemies/shotgunguy/walk_atlas.webp',
  walkCols: 4,
  walkRows: 5,
  deathTexName: 'SHOTGUNGUY_DEATH',
  deathUrl: '/game/enemies/shotgunguy/death_atlas.webp',
  deathFrames: 6,
  deathFps: 9,
  attackTexName: 'SHOTGUNGUY_ATTACK',
  attackUrl: '/game/enemies/shotgunguy/attack_shotgun.webp',
  attackFrames: 4,
  attackFps: 5, // timed so the muzzle flash (frame 2) lands ON the strike
  attackAspect: 272 / 590,
  painTexName: 'SHOTGUNGUY_PAIN',
  painUrl: '/game/enemies/shotgunguy/pain_atlas.webp',
  aspect: 704 / 776,
  worldHeight: 2,
  walkStepRate: 4.5,
  hitRadius: 0.5,
  hp: 150,
  speed: 0.9,
  standoff: 2.5,
  windup: 0.5,
  cooldownTime: 1.5,
  meleeReach: 1.3,
  meleeDamage: 12,
  shotgun: {
    range: 3.5,
    damage: 18,
  },
};

export const IMP_SPEC: EnemySpec = {
  texName: 'IMP_WALK',
  atlasUrl: '/game/enemies/imp/walk_atlas.webp',
  walkCols: 4,
  walkRows: 5,
  deathTexName: 'IMP_DEATH',
  deathUrl: '/game/enemies/imp/death_atlas.webp',
  deathFrames: 6,
  deathFps: 9,
  attackTexName: 'IMP_ATTACK',
  attackUrl: '/game/enemies/imp/attack_atlas.webp',
  attackFrames: 5,
  attackFps: 10,
  painTexName: 'IMP_PAIN',
  painUrl: '/game/enemies/imp/pain_atlas.webp',
  aspect: 600 / 717,
  worldHeight: 1.7,
  walkStepRate: 4.5,
  hitRadius: 0.35,
  hp: 45,
  speed: 1.8,
  standoff: 4,
  windup: 0.5,
  cooldownTime: 1.6,
  meleeReach: 1.2,
  meleeDamage: 8,
  thrower: {
    texName: 'IMP_CLIP',
    url: '/game/enemies/imp/clip_strip.webp',
    frames: 4,
    speed: 7,
    damage: 8,
    worldHeight: 0.4,
    aspect: 305 / 284,
    spinRate: 10,
    range: 12,
  },
};

export const LOSTSOUL_SPEC: EnemySpec = {
  texName: 'LOSTSOUL_WALK',
  atlasUrl: '/game/enemies/lostsoul/walk_atlas.webp',
  walkCols: 4,
  walkRows: 5,
  deathTexName: 'LOSTSOUL_DEATH',
  deathUrl: '/game/enemies/lostsoul/death_atlas.webp',
  deathFrames: 6,
  deathFps: 9,
  attackTexName: 'LOSTSOUL_ATTACK',
  attackUrl: '/game/enemies/lostsoul/attack_atlas.webp',
  attackFrames: 5,
  attackFps: 16,
  attackAspect: 332 / 451,
  painTexName: 'LOSTSOUL_PAIN',
  painUrl: '/game/enemies/lostsoul/pain_atlas.webp',
  aspect: 444 / 548,
  worldHeight: 1.85,
  walkStepRate: 5.5,
  hitRadius: 0.4,
  hp: 70,
  speed: 2.8,
  standoff: 0.7,
  windup: 0.3,
  cooldownTime: 0.9,
  meleeReach: 1.4,
  meleeDamage: 16,
};

export const ENEMY_SPECS: readonly EnemySpec[] = [
  PINKY_SPEC,
  SHOTGUNGUY_SPEC,
  IMP_SPEC,
  LOSTSOUL_SPEC,
];
