import type { Lang } from '../../domain';
import { SITE_ORIGIN } from './site';

/** Absolute URL of an article's social card (generated by `make og`, committed under `public/og/`). */
export function articleOgImage(slug: string, lang: Lang): string {
  return `${SITE_ORIGIN}/og/${slug}.${lang}.jpg`;
}
